latest

diff --git a/bin/venv-python b/bin/venv-python
--- a/bin/venv-python
+++ b/bin/venv-python
@@ -1,25 +1,47 @@
 #! /usr/bin/env bash
 
-# locus -----------------------------------------------------------------------
+# bash ------------------------------------------------------------------------
 
-readonly _DIRNAME=$( cd "$( dirname "${BASH_SOURCE[ 0 ]}" )" && pwd )
-readonly _BASENAME=$( basename ${BASH_SOURCE[ 0 ]} )
-readonly _ROOT=$( dirname ${_DIRNAME} )
+${BASH_DEBUG:+trap '(read -p "[${BASH_SOURCE}:${LINENO}] [${BASH_COMMAND}] ")' DEBUG}
+
+
+# location --------------------------------------------------------------------
+
+set -eu
+readonly _REALPATH=$(realpath "${BASH_SOURCE[ 0 ]}")
+readonly _BASENAME=$(basename "${_REALPATH}")
+readonly _DIRNAME=$(dirname "${_REALPATH}")
+readonly _ROOT=$(dirname "${_DIRNAME}")
+readonly _PREFIX=$(dirname "${_ROOT}")
 
 
 # environment -----------------------------------------------------------------
 
 export PYTHONDONTWRITEBYTECODE=1
 export PYTHONPATH=${_ROOT}/src/python/main/${PYTHONPATH:+:${PYTHONPATH}}
+export PYTHONPATH=${_ROOT}/lib/python/main/${PYTHONPATH:+:${PYTHONPATH}}
+
+
+# logging ---------------------------------------------------------------------
+
+function log { printf "%(%Y-%m-%d)T%(%H:%M:%S%z)T  ${@}\n" -1 ; }
+function err { printf "%(%Y-%m-%d)T%(%H:%M:%S%z)T  ${@}\n" -1 1>&2 ; }
+function banner {
+    log ""
+    log "-----------------------------------------------------------------------------"
+    log ">>> ${@}"
+    log "-----------------------------------------------------------------------------"
+}
 
 
 # execute ---------------------------------------------------------------------
 
-VENV_PYTHON=${_ROOT}/.venv/bin/python
-if [[ ! -f ${VENV_PYTHON} ]]; then 
-    echo "info: python binary [${VENV_PYTHON}] is missing.  Have you run 'bin/venv-init' ?"
-    exit 111
+readonly venv_python=${_ROOT}/.venv/bin/python
+if [[ ! -L ${venv_python} ]]; then 
+    err "error:  .venv/bin/python is missing."
+    err " note:  run bin/venv-create to create the .venv/ directory."
+    exit 1234
 fi
 
-exec ${VENV_PYTHON} "${@}"
+exec ${venv_python} "${@}"
 
